default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - commit

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-case-conflict
      - id: detect-private-key
  {% if cookiecutter.release_please|lower == 'y' -%}

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [fix, feat, chore, docs, feat!, chore!, fix!]

  {%- endif %}
  {% if cookiecutter.release_please|lower != 'y' -%}

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  {% endif -%}
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .markdownlint.yaml
          - --fix
        exclude: '^(CHANGELOG.md)$'
